Repository Azordev/dasher-user, pull requests merged in 2021-10, with the labels that each got.

#64 Add Router and all routes to pages
  package-lock.json
  package.json
  public/.htaccess
  public/_redirects
  src/index.js
  src/pages/Chat.jsx
  src/pages/Check.jsx
  src/pages/Confirm.jsx
  src/pages/Delivery.jsx
  src/pages/Error.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/pages/index.js
  yarn.lock
Labels: enhancement, help wanted, priority high, needs manual test, logic

#65 Add ErrorBoundary component
  src/layouts/ErrorBoundary.js
Labels: enhancement, priority medium, needs manual test, logic

#68 Feature/#17
  .github/workflows/main.yaml
  package-lock.json
  package.json
  public/index.html
  src/index.js
  src/pages/Home.jsx
  src/styles/breakpoints.js
  src/styles/colors.js
  src/styles/index.js
  src/styles/mixins.js
  src/styles/text.js
  src/styles/theme.js
  yarn.lock
Labels: enhancement, priority high, needs manual test

#71 Added support for GraphQl
  package-lock.json
  package.json
  src/index.js
  src/pages/Home.jsx
  src/services/GraphQl/client.js
  src/services/GraphQl/index.js
  src/services/GraphQl/mutations/index.js
  src/services/GraphQl/queries/index.js
  src/services/GraphQl/subscription/index.js
Labels: integration

#73 feat: add images and icons
  package-lock.json
  package.json
  src/assents/arrow-left.svg
  src/assents/asistant-chat.png
  src/assents/assistant.png
  src/assents/chat.png
  src/assents/close-icon.svg
  src/assents/delivery-chat-white.png
  src/assents/delivery-man.png
  src/assents/gps-icon.png
  src/assents/handshake.png
  src/assents/man-calification.png
  src/assents/note.png
  src/assents/send-chat.png
  src/assents/send.png
  src/assents/star.svg
  src/assents/ticket.png
  src/assents/user-icon.png
  src/assents/warning.png
  src/index.js
  src/pages/Chat.jsx
  src/pages/Check.jsx
  src/pages/Confirm.jsx
  src/pages/Delivery.jsx
  src/pages/Home.jsx
  yarn.lock
Labels: enhancement, needs manual test

#107 feat: add integration with subscription
  src/components/Input.jsx
  src/hooks/index.js
  src/hooks/useChats.js
  src/hooks/usePackage.js
  src/layouts/Chat.styled.jsx
  src/pages/Chat.jsx
  src/pages/Error.jsx
  src/services/GraphQl/mutations/chat.mutations.js
  src/services/GraphQl/mutations/index.js
  src/services/GraphQl/subscription/chat.subscriptions.js
  src/services/GraphQl/subscription/index.js
Labels: waiting for reviewer, needs manual test, logic, integration

#108 feat: add integration with query in form
  src/hooks/usePackage.js
  src/pages/Check.jsx
Labels: logic, integration
